name: Build and Deploy
on:
  push:
    branches:
      - blackjack

jobs:
  firebase-deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@blackjack
      - name: Setup Node
        uses: actions/setup-node@blackjack
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run test
      - run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@blackjack
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
